### ISSUE TITLE
Ipxe scripts, naming and confusion 

### ISSUE THREAD

**Issue by NiKiZe** [mintsoft/iPXE-WDS-EFI-Boot-Menu#3]
Hi,

Any particular reason why the files have .cfg or .conf extension.
We have had some users talking about iPXE config files, when they really where talking about these scripts.

The suggestion was to use the new `autoexec.ipxe` feature, but maybe windows TFTP server is blocking these unknown extensions?

https://github.com/ipxe/ipxe/issues/1327

**Comment by mintsoft** [comment]
There is no particular reason that I can recall and I don't remember there being any limitation on file types that the WDS TFTP server will send as long as it's under the Boot directory.

The WDS TFTP Trace logs might help out the person with the issue as they will show TFTP requests that are granted etc: https://learn.microsoft.com/en-us/troubleshoot/windows-server/setup-upgrade-and-drivers/enable-logging-windows-deployment-service#obtain-trace-logs-for-windows-server
